<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
 * Copyright 2004-2005 The Apache Software Foundation or its licensors,
 *                     as applicable.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 -->
<!DOCTYPE nodeTypes [
	<!ELEMENT nodeTypes (nodeType)*>
		<!ELEMENT nodeType (supertypes?|propertyDef*|childNodeDef*)>

		<!ATTLIST nodeType
			name CDATA #REQUIRED
			isMixin (true|false) #REQUIRED
 			hasOrderableChildNodes (true|false) #REQUIRED
			primaryItemName CDATA #REQUIRED
		>
		<!ELEMENT supertypes (supertype+)>
		<!ELEMENT supertype (CDATA)>

		<!ELEMENT propertyDef (valueConstraints?|defaultValues?)>
		<!ATTLIST propertyDef
			name CDATA #REQUIRED
			requiredType (String|Date|Path|Name|Reference|Binary|Double|Long|Boolean|undefined) #REQUIRED
			autoCreate (true|false) #REQUIRED
			mandatory (true|false) #REQUIRED
			onParentVersion (COPY|VERSION|INITIALIZE|COMPUTE|IGNORE|ABORT) #REQUIRED
			protected (true|false) #REQUIRED
			multiple  (true|false) #REQUIRED
		>
		<!ELEMENT valueConstraints (valueConstraint+)>
		<!ELEMENT valueConstraint (CDATA)>
		<!ELEMENT defaultValues (defaultValue+)>
		<!ELEMENT defaultValue (CDATA)>

		<!ELEMENT childNodeDef (requiredPrimaryTypes)>
		<!ATTLIST childNodeDef
			name CDATA #REQUIRED
			defaultPrimaryType  CDATA #REQUIRED
			autoCreate (true|false) #REQUIRED
			mandatory (true|false) #REQUIRED
			onParentVersion (COPY|VERSION|INITIALIZE|COMPUTE|IGNORE|ABORT) #REQUIRED
			protected (true|false) #REQUIRED
			sameNameSibs (true|false) #REQUIRED
		>
		<!ELEMENT requiredPrimaryTypes (requiredPrimaryType+)>
		<!ELEMENT requiredPrimaryType (CDATA)>
]>
<nodeTypes
    xmlns:rep="internal"
    xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    xmlns:mix="http://www.jcp.org/jcr/mix/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0">

    <!-- primary types -->
    <nodeType name="nt:base" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <propertyDef name="jcr:primaryType" requiredType="Name" autoCreate="true" mandatory="true" onParentVersion="COMPUTE" protected="true" multiple="false"/>
        <propertyDef name="jcr:mixinTypes" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="COMPUTE" protected="true" multiple="true"/>
    </nodeType>
    <nodeType name="nt:unstructured" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <childNodeDef name="*" defaultPrimaryType="nt:unstructured" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
        <propertyDef name="*" requiredType="undefined" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="true"/>
        <propertyDef name="*" requiredType="undefined" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:hierarchyNode" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:created" requiredType="Date" autoCreate="true" mandatory="true" onParentVersion="INITIALIZE" protected="true" multiple="false"/>
    </nodeType>
    <nodeType name="nt:file" isMixin="false" hasOrderableChildNodes="false" primaryItemName="jcr:content">
        <supertypes>
            <supertype>nt:hierarchyNode</supertype>
        </supertypes>
        <childNodeDef name="jcr:content" defaultPrimaryType="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:linkedFile" isMixin="false" hasOrderableChildNodes="false" primaryItemName="jcr:content">
        <supertypes>
            <supertype>nt:hierarchyNode</supertype>
        </supertypes>
        <propertyDef name="jcr:content" requiredType="Reference" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:folder" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:hierarchyNode</supertype>
        </supertypes>
        <childNodeDef name="*" defaultPrimaryType="" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:hierarchyNode</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:resource" isMixin="false" hasOrderableChildNodes="false" primaryItemName="jcr:data">
        <supertypes>
            <supertype>nt:base</supertype>
            <supertype>mix:referenceable</supertype>
        </supertypes>
        <propertyDef name="jcr:encoding" requiredType="String" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:mimeType" requiredType="String" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:data" requiredType="Binary" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:lastModified" requiredType="Date" autoCreate="false" mandatory="true" onParentVersion="IGNORE" protected="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:nodeType" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:nodeTypeName" requiredType="Name" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:supertypes" requiredType="Name" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="true"/>
        <propertyDef name="jcr:isMixin" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:hasOrderableChildNodes" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:primaryItemName" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
        <childNodeDef name="jcr:propertyDef" defaultPrimaryType="nt:propertyDef" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:propertyDef</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
        <childNodeDef name="jcr:childNodeDef" defaultPrimaryType="nt:childNodeDef" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:childNodeDef</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:propertyDef" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:name" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:autoCreate" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:mandatory" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:onParentVersion" requiredType="String" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:protected" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:requiredType" requiredType="String" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:valueConstraints" requiredType="String" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="true"/>
        <propertyDef name="jcr:defaultValues" requiredType="undefined" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="true"/>
        <propertyDef name="jcr:multiple" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:childNodeDef" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:name" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:autoCreate" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:mandatory" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:onParentVersion" requiredType="String" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:protected" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:requiredPrimaryTypes" requiredType="Name" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="true">
            <defaultValues>
                <defaultValue>{http://www.jcp.org/jcr/nt/1.0}base</defaultValue>
            </defaultValues>
        </propertyDef>
        <propertyDef name="jcr:defaultPrimaryType" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:sameNameSibs" requiredType="Boolean" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:versionHistory" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
            <supertype>mix:referenceable</supertype>
        </supertypes>
        <childNodeDef name="jcr:rootVersion" defaultPrimaryType="nt:version" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:version</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
        <childNodeDef name="jcr:versionLabels" defaultPrimaryType="nt:versionLabels" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:versionLabels</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
        <childNodeDef name="*" defaultPrimaryType="nt:version" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:version</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:versionLabels" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="*" requiredType="String" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true" />
    </nodeType>
    <nodeType name="nt:version" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
            <supertype>mix:referenceable</supertype>
        </supertypes>
        <propertyDef name="jcr:created" requiredType="Date" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" multiple="false"/>
        <propertyDef name="jcr:predecessors" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true">
            <valueConstraints>
                <valueConstraint>nt:version</valueConstraint>
            </valueConstraints>
        </propertyDef>
        <propertyDef name="jcr:successors" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true">
            <valueConstraints>
                <valueConstraint>nt:version</valueConstraint>
            </valueConstraints>
        </propertyDef>
        <childNodeDef name="jcr:frozenNode" defaultPrimaryType="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:frozenNode</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:frozenNode" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
            <supertype>mix:referenceable</supertype>
        </supertypes>
        <propertyDef name="jcr:frozenPrimaryType" requiredType="Name" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" multiple="false"/>
        <propertyDef name="jcr:frozenMixinTypes" requiredType="Name" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true"/>
        <propertyDef name="jcr:frozenUuid" requiredType="String" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" multiple="false"/>
        <propertyDef name="*" requiredType="undefined" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="false"/>
        <propertyDef name="*" requiredType="undefined" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true"/>
        <childNodeDef name="*" defaultPrimaryType="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="nt:versionedChild" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:child" requiredType="Reference" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" multiple="false">
            <valueConstraints>
                <valueConstraint>nt:versionHistory</valueConstraint>
            </valueConstraints>
        </propertyDef>
    </nodeType>
    <nodeType name="nt:query" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <propertyDef name="jcr:statement" requiredType="String" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
        <propertyDef name="jcr:language" requiredType="String" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="false"/>
    </nodeType>

    <!-- mixin types -->
    <nodeType name="mix:lockable" isMixin="true" hasOrderableChildNodes="false" primaryItemName="">
        <propertyDef name="jcr:lockOwner" requiredType="String" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="true" multiple="false"/>
        <propertyDef name="jcr:lockIsDeep" requiredType="Boolean" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="true" multiple="false"/>
    </nodeType>
    <nodeType name="mix:referenceable" isMixin="true" hasOrderableChildNodes="false" primaryItemName="">
        <propertyDef name="jcr:uuid" requiredType="String" autoCreate="true" mandatory="true" onParentVersion="INITIALIZE" protected="true" multiple="false"/>
    </nodeType>
    <nodeType name="mix:versionable" isMixin="true" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>mix:referenceable</supertype>
        </supertypes>
        <!-- spec defines this property as mandatory, but jackrabbit implementation needs it non-mandatory for proper initialization -->
        <propertyDef name="jcr:versionHistory" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="true" multiple="false">
            <valueConstraints>
                <valueConstraint>nt:versionHistory</valueConstraint>
            </valueConstraints>
        </propertyDef>
        <!-- spec defines this property as mandatory, but jackrabbit implementation needs it non-mandatory for proper initialization -->
        <propertyDef name="jcr:baseVersion" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="true" multiple="false">
            <valueConstraints>
                <valueConstraint>nt:version</valueConstraint>
            </valueConstraints>
        </propertyDef>
        <propertyDef name="jcr:isCheckedOut" requiredType="Boolean" autoCreate="true" mandatory="false" onParentVersion="IGNORE" protected="true" multiple="false">
            <defaultValues>
                <defaultValue>true</defaultValue>
            </defaultValues>
        </propertyDef>
        <!-- spec defines this property as mandatory, but jackrabbit implementation needs it non-mandatory for proper initialization -->
        <propertyDef name="jcr:predecessors" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="true" multiple="true">
            <valueConstraints>
                <valueConstraint>nt:version</valueConstraint>
            </valueConstraints>
        </propertyDef>
        <propertyDef name="jcr:mergeFailed" requiredType="Reference" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" multiple="true" />
    </nodeType>

    <!-- internal node types -->
    <nodeType name="rep:root" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:unstructured</supertype>
        </supertypes>
        <childNodeDef name="jcr:system" defaultPrimaryType="rep:system" autoCreate="false" mandatory="true" onParentVersion="IGNORE" protected="false" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>rep:system</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="rep:system" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <childNodeDef name="jcr:versionStorage" defaultPrimaryType="nt:unstructured" autoCreate="false" mandatory="true" onParentVersion="ABORT" protected="true" sameNameSibs="false">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
        <childNodeDef name="*" defaultPrimaryType="nt:unstructured" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="false" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <nodeType name="rep:versionStorage" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <childNodeDef name="*" defaultPrimaryType="nt:versionHistory" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" sameNameSibs="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:versionHistory</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDef>
    </nodeType>
    <!-- internal nodetypes for persistent version manager -->
    <nodeType name="rep:versionHistory" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:unstructured</supertype>
        </supertypes>
    </nodeType>
    <nodeType name="rep:version" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
        <supertypes>
            <supertype>nt:unstructured</supertype>
        </supertypes>
    </nodeType>
    <nodeType name="rep:frozen" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:unstructured</supertype>
        </supertypes>
    </nodeType>
    <nodeType name="rep:frozenVersionHistory" isMixin="false" hasOrderableChildNodes="true" primaryItemName="">
        <supertypes>
            <supertype>nt:unstructured</supertype>
        </supertypes>
    </nodeType>

</nodeTypes>